python BERT-NER-CHINESE \
    --do_train \
    --evaluate_during_training \
    --train_file BERT-NER-CHINESE/data/cner/train.char.bmes \
    --device cuda \
    --model_name_or_path bert-base-chinese \
    --load_entity_label_path BERT-NER-CHINESE/data/cner/ \
    --max_seq_length 128 \
    --batch_size 16 \
    --learning_rate 3e-5 \
    --adam_epsilon 1e-8 \
    --num_train_epochs 3 \
    --warmup_steps 0 \
    --output_dir BERT-NER-CHINESE/log/output \
    --evaluate_accumulation_steps 20